version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html/frontend
    overwrite: yes
permissions:
  - object: /usr/share/nginx/html/frontend
    owner: root
    group: root
    mode: 755
