name: React Build
on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code # 레포지토리 체크아웃
        uses: actions/checkout@prod

      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: npm run build
